---
env:
  #random seed for run
  rand_seed : 20240605
  #path to full pubmed corpus dataset (for help, see generating pubmed corpus github)
  dataset_path: '/mnt/scratch/ande2472/data/1147_latest.csv'
  #path to full pubmed corpus cleaned text
  clean_path: '/mnt/home/ande2472/data/bigdataoutput/complete_1147_clean_combined.pickle'
  #path to full pubmed corpus (Scibert) embedding matrix
  emb_path: '/mnt/home/ande2472/data/bigdataoutput/complete_1147_emb_combined.pickle'
  #path to journal list (for help, see generating pubmed corpus github)
  journals_dir: '/mnt/home/ande2472/data/full_clean_data/journalswISSN.csv'

  # Folder for storing generated data/model, recommended to pick place with lots of storage (like scratch)
  output_dir: '/mnt/scratch/ande2472/model_output/evo_bio_class_runs'
  # Subfolders for storing models and data (generated during run)
  model_dir_name: 'models'
  data_dir_name: 'data'


create_corpus:
  # Run name (None if not desired, if desired enter as string)
  run_name: ['trail_1_loose', 'trail_2_loose','trail_3_loose','trail_4_loose','trail_5_loose','trail_6_loose','trail_7_loose','trail_8_loose','trail_9_loose','trail_10_loose']
  # list of pubmed journals issns to be included in positive set
  issn_list: ['15452069','14712148','20419139','00143820','1525142X','20563744','17524571','15738477','2296701X','14209101','14321432','2041210X','15371719','1365294X','10557903','2397334X','1076836X','18728383','17596653','15375323','10960325']
  #Use the full positive set in dataset
  use_full_pos: True
  #if use_full_pos == false, number of positive samples to use
  num_pos: 2000
  #Ratio of positive to negative set for corpus
  pos_rate: .5
  #Percentage of dataset to be set aside for test set
  test_size: .2
  #Percentage of training set to be used for validation
  val_size: .25


model_hyperparams:
  w2v:
    dataframe_file: "/mnt/scratch/ande2472/model_output/evo_bio_class/test_filtered_data.tsv"
    txt_clean_file: "/mnt/scratch/ande2472/model_output/evo_bio_class/test_filtered_cleans.pickle"
    min_count: [5,10,20]
    window: 8
    ngram: [1,2,3]

    # Recommended to keep at default
    vector_size: 300
    sg: 1
    epochs: 30




...